version: "3.8"

services:
  elixir_app:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/elixir_db
    depends_on:
      - db
    command: mix phx.server

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elixir_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
